dist: trusty
language: node_js
node_js:
  - '8' 

cache:
  directories:
    - node_modules

script:
  - yarn && yarn build
  
deploy:
  local_dir: ./dist
  target_branch: gh-pages
  keep_history: true
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
