dist: trusty

language: node_js

node_js:
  - '8' 

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - yarn && yarn build

deploy:
  local_dir: ./dist
  keep_history: true
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: gh-pages
